---
- name: "Get Installed Versions Of {{ sdkman_package.key }}"
  ansible.builtin.shell:
    cmd: "ls $SDKMAN_CANDIDATES_DIR/{{ sdkman_package.key }} || echo"
  register: sdkman_package_installed_versions
  changed_when: false

- name: "Install SDKMAN Package"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      source "{{ role_path }}/files/sdkman.sh"
      sdk install {{ sdkman_package.key }} {{ sdkman_package.value }}
  when: sdkman_package.value not in sdkman_package_installed_versions.stdout_lines
  changed_when: true
