---
- name: "Create {{ sdkman_temp_dir }}"
  ansible.builtin.file:
    path: "{{ sdkman_temp_dir }}"
    state: directory
    mode: "0755"

- name: "Download SDKMAN Installer"
  ansible.builtin.get_url:
    url: "https://get.sdkman.io"
    dest: "{{ sdkman_temp_dir }}"
    mode: "0755"
  register: sdkman_installer

- name: "Install SDKMAN" # noqa: no-handler
  ansible.builtin.command:
    cmd: "{{ sdkman_installer.dest }}"
  changed_when: true
  when: sdkman_installer.changed

- name: "Config Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ shared_env_sh.dest }}"
    create: true
    mode: "0644"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ role_path }}/files/sdkman.sh

- name: "Install SDKMAN Packages"
  ansible.builtin.include_tasks: "install.yaml"
  loop: "{{ sdkman_packages | dict2items }}"
  loop_control:
    loop_var: sdkman_package
