---
- name: "Check 1Password System Installation"
  ansible.builtin.shell:
    cmd: mdfind "kMDItemKind = Application && kMDItemDisplayName = 1Password"
  register: onepassword_op_installed_by_system
  changed_when: false

- name: "Install 1password"
  community.general.homebrew_cask:
    state: latest
    name:
      - 1password
  when: onepassword_op_installed_by_system.stdout|length == 0

- name: "Install 1password-cli"
  community.general.homebrew_cask:
    state: latest
    name:
      - 1password-cli
