- hosts: localhost
  roles:
    - age
    - awscli
    - base
    - bazelisk
    - colorscheme
    - coreutils
    - docker
    - flux
    - gitconfig
    - gnupg
    - go-task
    - helm
    - homebrew-dependencies
    - intellij
    - kubeconform
    - kustomize
    - neovim
    - nerdfonts
    - node
    - ohmyzsh
    - podman
    - poetry
    - pyenv
    - rbenv
    - rustup
    - sdkman
    - shell-env
    - sops
    - talosctl
    - tfenv
    - tmux
    - yq
