---
- name: "Create bash-env.sh"
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/.generated/bash-env.sh"
    content: ""
    force: false
    mode: "0644"
  register: bash_env_sh

- name: "Source Shared Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ bash_env_sh.dest }}"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ shared_env_sh.dest }}
    create: true
    mode: "0644"

- name: "Add To User Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env'].HOME }}/.bashrc"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ bash_env_sh.dest }}
    create: true
    mode: "0644"
