---
- name: "Create Shared Shell Env"
  ansible.builtin.copy:
    dest: "{{playbook_dir}}/.generated/shared-env.sh"
    content: ""
    force: false
  register: SHARED_ENV_SH

- name: Setup Shell Env
  ansible.builtin.include_tasks: "{{shell}}.yaml"
  loop_control:
    loop_var: shell
  loop:
    - bash
    - zsh
