---
- name: "Create zsh-env.sh"
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/.generated/zsh-env.sh"
    content: ""
    force: false
    mode: "0644"
  register: zsh_env_sh

- name: "Source Shared Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ zsh_env_sh.dest }}"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ shared_env_sh.dest }}
    create: true
    mode: "0644"

- name: "Add To User Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts['env'].HOME }}/.zshrc"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ zsh_env_sh.dest }}
    create: true
    mode: "0644"
