---
- name: "Install intellij-idea"
  community.general.homebrew_cask:
    state: latest
    name: intellij-idea

- name: "Get intellij-idea Version"
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail &&
      brew info --cask --json=v2 intellij-idea |
      jq --raw-output '.casks[0].version | split(",")[]'
    executable: /bin/bash
  register: intellij_idea_current_version
  changed_when: false

- name: "Set IDEA version Fact"
  ansible.builtin.set_fact:
    intellij_idea_version: "{{ intellij_idea_current_version.stdout_lines[0] }}"
    intellij_idea_build: "{{ intellij_idea_current_version.stdout_lines[1] }}"
