---
- name: "Install intellij-idea-ce"
  community.general.homebrew_cask:
    state: latest
    name: intellij-idea-ce

- name: "Get intellij-idea-ce Version"
  ansible.builtin.shell:
    cmd: brew info --cask --json=v2 intellij-idea-ce | jq --raw-output '.casks[0].version | split(",")[]'
  register: IDEA_CURRENT_VERSION
  changed_when: false

- name: "Set IDEA version Fact"
  ansible.builtin.set_fact:
    IDEA_VERSION: "{{IDEA_CURRENT_VERSION.stdout_lines[0]}}"
    IDEA_BUILD: "{{IDEA_CURRENT_VERSION.stdout_lines[1]}}"

