---
- name: "Get intellij-idea-ce Version"
  ansible.builtin.shell:
    cmd: brew info --cask intellij-idea-ce | grep --extended-regex --only-matching '202[0-9]\.[^,]+'
  register: IDEA_CURRENT_VERSION

- name: "Set IDEA_BUILD Fact"
  ansible.builtin.set_fact:
    IDEA_BUILD: "{{IDEA_CURRENT_VERSION.stdout}}"

