---
- name: "Include Variables - {{ ansible_facts['system'] }}"
  ansible.builtin.include_vars: "{{ ansible_facts['system'] | lower }}.yaml"

- name: "Get intellij-idea Version" # noqa: command-instead-of-module
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail &&
      curl --silent https://data.services.jetbrains.com/products/releases?code=IIC |
      jq --raw-output '.IIC[0] | [.version, .build, .downloads.linux.link][]'
    executable: /bin/bash
  register: intellij_idea_latest_version
  changed_when: false

- name: "Set IDEA version Fact"
  ansible.builtin.set_fact:
    intellij_idea_version: "{{ intellij_idea_latest_version.stdout_lines[0] }}"
    intellij_idea_build: "{{ intellij_idea_latest_version.stdout_lines[1] }}"
    intellij_idea_download_url: "{{ intellij_idea_latest_version.stdout_lines[2] }}"

- name: "Create {{ intellij_idea_bin_dir }}"
  ansible.builtin.file:
    path: "{{ intellij_idea_bin_dir }}"
    state: directory
    mode: "0755"
  become: true

- name: "Create {{ intellij_idea_current_dir }}"
  ansible.builtin.file:
    path: "{{ intellij_idea_current_dir }}"
    state: directory
    mode: "0755"
  become: true
  register: intellij_idea_current

- name: "Download intellij-idea" # noqa: no-handler
  ansible.builtin.get_url:
    url: "{{ intellij_idea_download_url }}"
    dest: "{{ intellij_idea_temp_dir }}"
    mode: "0644"
  register: intellij_idea_installer
  when: intellij_idea_current.changed

- name: "Unarchive intellij-idea" # noqa: no-handler
  ansible.builtin.unarchive:
    src: "{{ intellij_idea_installer.dest }}"
    dest: "{{ intellij_idea_current_dir }}"
    remote_src: true
    extra_opts:
      - "--strip-components=1"
      - "--ungzip"
    mode: "0755"
  become: true
  when: intellij_idea_installer.changed

- name: "Create Symlink For idea"
  ansible.builtin.file:
    path: "{{ intellij_idea_bin_dir }}/idea"
    src: "{{ intellij_idea_current_dir }}/bin/idea"
    state: link
  become: true

- name: "Setup Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ shared_env_sh.dest }}"
    create: true
    mode: "0644"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: export PATH="{{ intellij_idea_bin_dir }}:$PATH"
