---
- name: Include {{ansible_system}} Variables
  ansible.builtin.include_vars: "{{ansible_system|lower}}.yaml"

- name: "Get intellij-idea-ce Version"
  ansible.builtin.shell:
    cmd: curl --silent https://data.services.jetbrains.com/products/releases?code=IIC | jq --raw-output '.IIC[0] | [.version, .build, .downloads.linux.link][]'
  register: IDEA_LATEST_VERSION
  changed_when: false

- name: "Set IDEA version Fact"
  ansible.builtin.set_fact:
    IDEA_VERSION: "{{IDEA_LATEST_VERSION.stdout_lines[0]}}"
    IDEA_BUILD: "{{IDEA_LATEST_VERSION.stdout_lines[1]}}"
    IDEA_DOWNLOAD_URL: "{{IDEA_LATEST_VERSION.stdout_lines[2]}}"

- name: "Create {{IDEA_BIN_DIR}}"
  ansible.builtin.file:
    path: "{{IDEA_BIN_DIR}}"
    state: directory
    mode: "0755"
  become: yes

- name: "Create {{IDEA_CURRENT_DIR}}"
  ansible.builtin.file:
    path: "{{IDEA_CURRENT_DIR}}"
    state: directory
    mode: "0755"
  become: yes
  register: IDEA_CURRENT

- name: "Download intellij-idea-ce"
  ansible.builtin.get_url:
    url: "{{IDEA_DOWNLOAD_URL}}"
    dest: "{{IDEA_TEMP_DIR}}"
  register: IDEA_INSTALLER
  when: IDEA_CURRENT.changed

- name: "Unarchive {{IDEA_INSTALLER.dest|basename}}"
  ansible.builtin.unarchive:
    src: "{{IDEA_INSTALLER.dest}}"
    dest: "{{IDEA_CURRENT_DIR}}"
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
      - "--ungzip"
  become: yes
  when: IDEA_INSTALLER.changed

- name: "Create Symlink {{IDEA_BIN_DIR}}/idea"
  ansible.builtin.file:
    path: "{{IDEA_BIN_DIR}}/idea"
    src: "{{IDEA_CURRENT_DIR}}/bin/idea"
    state: link
  become: yes

- name: "Setup Shell Env"
  ansible.builtin.blockinfile:
    path: "{{SHARED_ENV_SH.dest}}"
    create: yes
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{playbook_dir|basename}}/roles/{{role_name}} ####"
    block: export PATH="{{IDEA_BIN_DIR}}:$PATH"

