---
- name: "Create {{ intellij_idea_temp_dir }}"
  ansible.builtin.file:
    path: "{{ intellij_idea_temp_dir }}"
    state: directory
    mode: "0755"

- name: Install IntelliJ IDEA
  ansible.builtin.include_tasks: "{{ ansible_facts['system'] | lower }}.yaml"

- name: "Create IntelliJ IDEA Plugins Directory"
  ansible.builtin.file:
    path: "{{ intellij_idea_plugins_dir[ansible_facts['system'] | lower] }}"
    state: directory
    mode: "0775"
  register: intellij_idea_current_plugins_dir

- name: "Install Plugins"
  ansible.builtin.include_tasks: plugin.yaml
  loop: "{{ intellij_idea_plugins }}"
  loop_control:
    loop_var: intellij_idea_plugin
