---
- name: "Download {{ intellij_idea_plugin }}"
  ansible.builtin.get_url:
    url: "https://plugins.jetbrains.com/pluginManager?action=download&id={{ intellij_idea_plugin | urlencode }}&build={{ intellij_idea_build }}"
    dest: "{{ intellij_idea_temp_dir }}"
    mode: "0644"
  register: intellij_idea_plugin_archive

- name: "Unarchive {{ intellij_idea_plugin_archive.dest | basename }}"
  ansible.builtin.unarchive:
    src: "{{ intellij_idea_plugin_archive.dest }}"
    dest: "{{ intellij_idea_current_plugins_dir.path }}"
    remote_src: true
    mode: "0755"
  when: intellij_idea_plugin_archive.changed and intellij_idea_plugin_archive.dest.endswith(".zip")

- name: "Copy {{ intellij_idea_plugin_archive.dest | basename }}"
  ansible.builtin.copy:
    src: "{{ intellij_idea_plugin_archive.dest }}"
    dest: "{{ intellij_idea_current_plugins_dir.path }}"
    mode: "0644"
  when: intellij_idea_plugin_archive.changed and intellij_idea_plugin_archive.dest.endswith(".jar")
