---
REQUIRED_PACKAGES:
  debian:
    - build-essential
    - coreutils
    - curl
    - dbus-x11
    - dconf-cli
    - git
    - gnome-terminal
    - libffi-dev
    - libglib2.0-bin
    - libssl-dev
    - python3-apt
    - python3-venv
    - tmux
    - unzip
    - uuid-runtime
    - zip
    - zlib1g-dev
    - zsh

OPTIONAL_PACKAGES:
  debian:
    - ca-certificates
    - fswatch
    - gnupg
    - graphviz
    - hunspell
    - jq
    - man-db
    - ripgrep
    - tree
    - wget

