---
- name: "Tap peonping"
  community.general.homebrew_tap:
    name: peonping/tap

- name: "Install peon-ping"
  community.general.homebrew:
    state: latest
    name: peon-ping

- name: "Run peon-ping-setup"
  ansible.builtin.shell: peon-ping-setup
  args:
    creates: "{{ansible_facts['env'].HOME}}/.claude/hooks/peon-ping/peon.sh"
    executable: /bin/bash
  when: "(ansible_facts['env'].HOME + '/.claude') is directory"
