---
- name: "Install coreutils"
  community.general.homebrew:
    state: latest
    name: coreutils

- name: "Setup Shell Env For coreutils"
  ansible.builtin.blockinfile:
    path: "{{SHARED_ENV_SH.dest}}"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{playbook_dir|basename}}/roles/{{role_name}} ####"
    create: yes
    block: |
      export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"

