---
- name: "Install coreutils"
  community.general.homebrew:
    state: latest
    name: coreutils

- name: "Setup Shell Env For coreutils"
  ansible.builtin.blockinfile:
    path: "{{ shared_env_sh.dest }}"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    create: true
    mode: "0644"
    block: |
      export PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"
