---
- name: "Include Variables - {{ nerdfonts_terminals[ansible_facts['system'] | lower] }}"
  ansible.builtin.include_vars: "{{ nerdfonts_terminals[ansible_facts['system'] | lower] }}.yaml"

- name: "Find Default Profile"
  ansible.builtin.shell:
    cmd: "set -o pipefail && gsettings get {{ nerdfonts_gsettings_profilelist_path }} default | tr -d \\'"
    executable: /bin/bash
  changed_when: false
  register: nerdfonts_gnome_default_profile

- name: "Get Current Font Of Default Profile"
  ansible.builtin.command:
    cmd: "dconf read {{ nerdfonts_dconf_profile_base_path }}:/:{{ nerdfonts_gnome_default_profile.stdout }}/font"
  changed_when: false
  register: nerdfonts_nerd_fonts_current

- name: "Use Font For Default Profile - {{ nerdfonts_font.NAME }}"
  ansible.builtin.command:
    cmd: >-
      dbus-run-session dconf write
      {{ nerdfonts_dconf_profile_base_path }}:/:{{ nerdfonts_gnome_default_profile.stdout }}/font
      "'{{ nerdfonts_font.NAME }} {{ nerdfonts_font.SIZE }}'"
  when: nerdfonts_font.NAME not in nerdfonts_nerd_fonts_current.stdout
  changed_when: true

- name: "Enable Custom Font For Default Profile"
  ansible.builtin.command:
    cmd: "dbus-run-session dconf write {{ nerdfonts_dconf_profile_base_path }}:/:{{ nerdfonts_gnome_default_profile.stdout }}/use-system-font false"
  when: nerdfonts_font.NAME not in nerdfonts_nerd_fonts_current.stdout
  changed_when: true
