---
- name: "Install tfenv"
  community.general.homebrew:
    state: latest
    name: tfenv

- name: "Get Latest Terraform Version"
  ansible.builtin.shell:
    cmd: tfenv list-remote | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1
  register: TERRAFORM_LATEST
  changed_when: false

- name: "Get Installed Terraform Version"
  ansible.builtin.shell:
    cmd: tfenv list | grep --extended-regexp --only-matching --color=never '[0-9]+\.[0-9]+\.[0-9]+' || echo 'N/A'
  register: TERRAFORM_INSTALLED
  changed_when: false

- name: "Install Latest Terraform Version"
  ansible.builtin.shell:
    cmd: "tfenv install latest"
  when: TERRAFORM_LATEST.stdout not in TERRAFORM_INSTALLED.stdout_lines
