---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/refs/heads/main/src/ansiblelint/schemas/tasks.json
- name: "Install Packages - {{ ansible_facts['distribution'] }}"
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - curl
      - file
      - git
      - procps-ng
      - python3-libdnf5
