---
- name: "Install Rust"
  community.general.homebrew:
    state: latest
    name: rust

- name: "Config Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ shared_env_sh.dest }}"
    create: true
    mode: "0644"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ role_path }}/files/cargo.sh

- name: "List Installed Packages"
  ansible.builtin.shell:
    cmd: set -o pipefail && cargo install --list | grep --extended-regex --only-matching --color=never '^[^ ]+' || true
    executable: /bin/bash
  register: rustup_cargo_installed_versions
  changed_when: false

- name: "Install Cargo Packages"
  ansible.builtin.command:
    cmd: cargo install {{ item.key }} --version {{ item.value }}
  loop: "{{ rustup_cargo_packages | dict2items }}"
  changed_when: true
  when: "item.key + ' v' + item.value + ':' not in rustup_cargo_installed_versions.stdout_lines"
