---
- name: "Install Rust"
  community.general.homebrew:
    state: latest
    name: rust

- name: "Config Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ shared_env_sh.dest }}"
    create: true
    mode: "0644"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ role_path }}/files/cargo.sh

- name: "List Installed Packages"
  ansible.builtin.shell:
    cmd: set -o pipefail && cargo install --list | grep --extended-regex --only-matching --color=never '^[^ ]*' || echo 'N/A'
    executable: /bin/bash
  register: rustup_cargo_installed_versions
  changed_when: false

- name: "Install Cargo Packages"
  ansible.builtin.command:
    cmd: cargo install {{ cargo_package }}
  loop: "{{ rustup_cargo_packages }}"
  loop_control:
    loop_var: cargo_package
  changed_when: true
  when: cargo_package not in rustup_cargo_installed_versions.stdout_lines
