---
HOMEBREW_CASK_PACKAGES:
  - firefox
  - intellij-idea-ce
  - iterm2
  - rectangle
  - stats

HOMEBREW_PACKAGES:
  - coreutils
  - gnu-getopt
  - gnu-tar
  - gnupg
  - grep
  - jq
  - lcov
  - ncdu
  - openssl
  - pinentry-mac
  - python3
  - ripgrep
  - shellcheck
  - tree
  - zsh

