[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export BAT_THEME="Nord"
export EDITOR='nvim'
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export GPG_TTY=$(tty)
export PAGER='bat'
export ZSH_TMUX_AUTOQUIT=false
export ZSH_TMUX_AUTOSTART=true

source $HOME/.oh-my-zsh.zshrc
source $HOME/.p10k.zsh
