---
- name: Include {{ansible_system}} Variables
  ansible.builtin.include_vars: "{{ansible_system|lower}}.yaml"

- name: "Create {{BAZELISK_CURRENT_DIR}}"
  ansible.builtin.file:
    path: "{{BAZELISK_CURRENT_DIR}}"
    state: directory
    mode: "0755"
  become: yes
  register: BAZELISK_CURRENT

- name: "Create {{BAZELISK_TEMP_DIR}}"
  ansible.builtin.file:
    path: "{{BAZELISK_TEMP_DIR}}"
    state: directory

- name: "Download bazelisk"
  ansible.builtin.get_url:
    url: "https://github.com/bazelbuild/bazelisk/releases/download/{{BAZELISK_BUILD}}/bazelisk-linux-amd64"
    dest: "{{BAZELISK_TEMP_DIR}}"
  register: BAZELISK_BINARY

- name: "Copy bazelisk to {{BAZELISK_CURRENT_DIR}}"
  ansible.builtin.copy:
    src: "{{BAZELISK_BINARY.dest}}"
    dest: "{{BAZELISK_CURRENT_DIR}}"
    mode: "0755"
  become: yes
  when: BAZELISK_BINARY.changed

- name: "Symlink bazelisk to {{USR_LOCAL_BIN_DIR}}/bazelisk"
  ansible.builtin.file:
    path: "{{USR_LOCAL_BIN_DIR}}/bazelisk"
    src: "{{BAZELISK_CURRENT_DIR}}/bazelisk-linux-amd64"
    state: link
  become: yes

