---
- name: "Install tmux"
  community.general.homebrew:
    state: latest
    name: tmux

- name: "Create {{TMUX_PLUGIN_DIR}}"
  ansible.builtin.file:
    path: "{{TMUX_PLUGIN_DIR}}"
    state: directory

- name: "Git Clone tmux-plugins/tpm"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{TMUX_PLUGIN_DIR}}/tpm"
  register: TFENV_REPO

- name: "Git Clone tmux-plugins/tpm"
  ansible.builtin.blockinfile:
    path: "{{ansible_env.HOME}}/.tmux.conf"
    create: yes
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{playbook_dir|basename}}/roles/{{role_name}} ####"
    block: source-file "{{role_path}}/files/tmux.conf"

- ansible.builtin.shell:
    cmd: "{{ansible_env.HOME}}/.tmux/plugins/tpm/bin/install_plugins"
  changed_when: false

