---
- name: "Install Node"
  community.general.homebrew:
    state: latest
    name: node

- name: "Install Node Packages"
  community.general.npm:
    name: "{{ package }}"
    global: true
  loop_control:
    loop_var: package
  loop: "{{ node_packages }}"
