---
- name: "Get android-studio Version"
  ansible.builtin.shell:
    cmd: brew info --cask android-studio | grep --extended-regex --only-matching '202[0-9]\.[^,]+'
  register: ANDROID_STUDIO_CURRENT_VERSION
  changed_when: false

- name: "Set ANDROID_STUDIO_BUILD Fact"
  ansible.builtin.set_fact:
    ANDROID_STUDIO_BUILD: "{{ANDROID_STUDIO_CURRENT_VERSION.stdout}}"

