---
- name: "Install pyenv"
  community.general.homebrew:
    state: latest
    name:
      - pyenv
      - pyenv-virtualenv

- name: "List Installed Versions"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      pyenv versions --bare
  register: pyenv_python_installed_versions
  changed_when: false

- name: "Install Python Versions"
  ansible.builtin.include_tasks: "install.yaml"
  loop: "{{ pyenv_python_versions }}"
  loop_control:
    loop_var: python_version
  when: python_version not in pyenv_python_installed_versions.stdout_lines

- name: "Check Global Python Version"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      pyenv global
  register: pyenv_python_global_version
  changed_when: false

- name: "Set Global Python Version"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      pyenv global {{ pyenv_python_versions[-1] }}
  changed_when: true
  when: pyenv_python_versions|last != pyenv_python_global_version.stdout
