---
- name: "Install pyenv"
  community.general.homebrew:
    state: latest
    name:
      - pyenv
      - pyenv-virtualenv

- name: "List Installed Versions"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      pyenv versions --bare
  register: PYTHON_INSTALLED_VERSIONS
  changed_when: false

- name: "Install Python Versions"
  ansible.builtin.include_tasks: "install.yaml"
  loop: "{{PYTHON_VERSIONS}}"
  loop_control:
    loop_var: python_version
  when: python_version not in PYTHON_INSTALLED_VERSIONS.stdout_lines

- name: "Set Global Python Version"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      pyenv global {{PYTHON_VERSIONS[-1]}}
  when: PYTHON_VERSIONS|last != PYTHON_INSTALLED_VERSIONS.stdout_lines|last|default('N/A')

