---
- name: "Install Packages - {{ ansible_facts['distribution'] }}"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ base_required_packages['fedora'] + base_optional_packages['fedora'] }}"
