---
- name: "Create APT Keyrings Directory"
  become: yes
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    mode: '0755'

- name: "Create Temp Dir"
  ansible.builtin.file:
    path: "/tmp/ansible.roles.docker"
    state: directory
  register: DOCKER_TEMP

- name: "Download Docker Signing Key"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg
    dest: "{{DOCKER_TEMP.path}}"
  register: DOCKER_REPO_KEY

- name: "Dearmor Docker Signing Key"
  ansible.builtin.shell:
    cmd: "gpg --batch --yes --output {{DOCKER_TEMP.path}}/dearmored.docker.gpg --dearmor {{DOCKER_REPO_KEY.dest}}"
  changed_when: DOCKER_REPO_KEY.changed

- name: "Copy Docker Signing Key To Keyrings"
  ansible.builtin.copy:
    src: "{{DOCKER_TEMP.path}}/dearmored.docker.gpg"
    dest: "/etc/apt/keyrings/docker.gpg"
  become: yes

- name: "Get OS Arch"
  ansible.builtin.shell: dpkg --print-architecture
  register: ARCH
  changed_when: false

- name: "Add APT Source List"
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch={{ARCH.stdout}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"
    mode: '0644'
  become: yes

