---
- name: Install {{ansible_distribution}} Packages
  become: yes
  ansible.builtin.apt:
    state: latest
    name:
      - acl
      - automake
      - autotools-dev
      - bison
      - build-essential
      - ca-certificates
      - coreutils
      - curl
      - dconf-cli
      - fswatch
      - fuse-overlayfs
      - git
      - gnome-terminal
      - gnupg
      - graphviz
      - hunspell
      - jq
      - less
      - libbluetooth-dev
      - libbz2-dev
      - libevent-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libxtst6
      - llvm
      - locales
      - lsb-release
      - man-db
      - podman
      - procps
      - ripgrep
      - slirp4netns
      - taskwarrior
      - tk-dev
      - tmux
      - tree
      - uidmap
      - uuid-dev
      - wget
      - xz-utils
      - zip
      - zlib1g-dev
      - zsh
