---
- name: "Setup Shell Env For Homebrew"
  ansible.builtin.blockinfile:
    path: "{{SHARED_ENV_SH.dest}}"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{playbook_dir|basename}}/roles/{{role_name}} ####"
    create: yes
    block: |
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

- name: Install Common Packages
  become: yes
  ansible.builtin.package:
    state: latest
    name: "{{REQUIRED_PACKAGES['common'] + OPTIONAL_PACKAGES['common']}}"

- name: Install {{ansible_distribution}} Packages
  ansible.builtin.include_tasks:
    file: "distros/{{ansible_distribution|lower}}.yaml"

