---
- name: Install Common Packages
  become: yes
  ansible.builtin.package:
    state: latest
    name: "{{REQUIRED_PACKAGES['common'] + OPTIONAL_PACKAGES['common']}}"

- name: Install {{ansible_distribution}} Packages
  ansible.builtin.include_tasks:
    file: "distros/{{ansible_distribution|lower}}.yaml"

