---
- name: "Include Variables - {{ ansible_facts['system'] }}"
  ansible.builtin.include_vars: "{{ ansible_facts['system'] | lower }}.yaml"

- name: "Install Packages - {{ ansible_facts['system'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['system'] | lower }}.yaml"
