---
- name: "Create {{shell}} Env Script"
  ansible.builtin.copy:
    dest: "{{playbook_dir}}/.generated/{{shell}}-env.sh"
    content: ""
    force: false
  register: ZSH_ENV_SH

- name: "Source Shared Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ZSH_ENV_SH.dest}}"
    create: yes
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{playbook_dir|basename}}/roles/{{role_name}} ####"
    block: source {{SHARED_ENV_SH.dest}}

- name: "Add To User Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ansible_env.HOME}}/{{SHELLS[shell]}}"
    create: yes
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{playbook_dir|basename}}/roles/{{role_name}} ####"
    block: source {{ZSH_ENV_SH.dest}}

