---
- name: "Install Ruby {{ruby_version}}"
  ansible.builtin.shell:
    executable: "{{ZSH_PATH}}"
    cmd: |
      source {{role_path}}/files/rbenv.sh
      rbenv install --skip-existing {{ruby_version}}

- name: "Find Installed Packages"
  ansible.builtin.shell:
    executable: "{{ZSH_PATH}}"
    cmd: |
      source {{role_path}}/files/rbenv.sh
      RBENV_VERSION={{ruby_version}} rbenv exec gem list | grep --extended-regex --only-matching --color=never '^[^ ]*'
  register: GEM_INSTALLED_PACKAGES
  changed_when: false

- name: "Install Gem Packages"
  ansible.builtin.shell:
    executable: "{{ZSH_PATH}}"
    cmd: |
      source {{role_path}}/files/rbenv.sh
      RBENV_VERSION={{ruby_version}} rbenv exec gem install {{gem_package}}
  loop_control:
    loop_var: gem_package
  loop: "{{GEM_PACKAGES}}"
  changed_when: gem_package not in GEM_INSTALLED_PACKAGES.stdout_lines

