---
- name: "Install rbenv"
  community.general.homebrew:
    state: latest
    name: rbenv

- name: "List Installed Versions"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      rbenv versions --bare
  register: RUBY_INSTALLED_VERSIONS
  changed_when: false

- name: "Install Ruby Versions"
  ansible.builtin.include_tasks: "install.yaml"
  loop: "{{RUBY_VERSIONS}}"
  loop_control:
    loop_var: ruby_version
  when: ruby_version not in RUBY_INSTALLED_VERSIONS.stdout_lines

- name: "Set Global Ruby Version"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      rbenv global {{RUBY_VERSIONS[-1]}}
  when: RUBY_VERSIONS|last != RUBY_INSTALLED_VERSIONS.stdout_lines|last|default('N/A')

