---
- name: "Install rbenv"
  community.general.homebrew:
    state: latest
    name:
      - rbenv
      - ruby-build

- name: "Config Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ shared_env_sh.dest }}"
    create: true
    mode: "0644"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ role_path }}/files/rbenv.sh

- name: "List Installed Versions"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      source {{ role_path }}/files/rbenv.sh
      rbenv versions --bare
  register: rbenv_ruby_installed_versions
  changed_when: false

- name: "Install Ruby Versions"
  ansible.builtin.include_tasks: "install.yaml"
  loop: "{{ rbenv_ruby_versions }}"
  loop_control:
    loop_var: ruby_version
  when: ruby_version not in rbenv_ruby_installed_versions.stdout_lines

- name: "Set Global Ruby Version"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      source {{ role_path }}/files/rbenv.sh
      rbenv global {{ rbenv_ruby_versions[-1] }}
  changed_when: true
  when: rbenv_ruby_versions|last != rbenv_ruby_installed_versions.stdout_lines|last|default('N/A')
