---
- name: "Install rbenv"
  community.general.homebrew:
    state: latest
    name: rbenv

- name: "Config Shell Env"
  ansible.builtin.blockinfile:
    path: "{{SHARED_ENV_SH.dest}}"
    create: yes
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{playbook_dir|basename}}/roles/{{role_name}} ####"
    block: source {{role_path}}/files/rbenv.sh

- name: "List Installed Versions"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      source {{role_path}}/files/rbenv.sh
      rbenv versions --bare
  register: RUBY_INSTALLED_VERSIONS
  changed_when: false

- name: "Install Ruby Versions"
  ansible.builtin.include_tasks: "install.yaml"
  loop: "{{RUBY_VERSIONS}}"
  loop_control:
    loop_var: ruby_version
  when: ruby_version not in RUBY_INSTALLED_VERSIONS.stdout_lines

- name: "Set Global Ruby Version"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      source {{role_path}}/files/rbenv.sh
      rbenv global {{RUBY_VERSIONS[-1]}}
  when: RUBY_VERSIONS|last != RUBY_INSTALLED_VERSIONS.stdout_lines|last|default('N/A')

