---
- name: "Create {{NEOVIM_BIN_DIR}}"
  ansible.builtin.file:
    path: "{{NEOVIM_BIN_DIR}}"
    state: directory
    mode: "0755"
  become: yes

- name: "Create {{NEOVIM_CURRENT_DIR}}"
  ansible.builtin.file:
    path: "{{NEOVIM_CURRENT_DIR}}"
    state: directory
    mode: "0755"
  become: yes
  register: NEOVIM_CURRENT

- name: "Create {{NEOVIM_TEMP_DIR}}"
  ansible.builtin.file:
    path: "{{NEOVIM_TEMP_DIR}}"
    state: directory

- name: "Download nvim.appimage"
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{NEOVIM_BUILD}}/nvim.appimage"
    dest: "{{NEOVIM_TEMP_DIR}}"
  register: NEOVIM_APPIMAGE

- name: "Copy nvim.appimage to {{NEOVIM_CURRENT_DIR}}"
  ansible.builtin.copy:
    src: "{{NEOVIM_APPIMAGE.dest}}"
    dest: "{{NEOVIM_CURRENT_DIR}}"
    mode: "0755"
  become: yes

- name: "Symlink nvim.appimage to {{NEOVIM_BIN_DIR}}/nvim"
  ansible.builtin.file:
    path: "{{NEOVIM_BIN_DIR}}/nvim"
    src: "{{NEOVIM_CURRENT_DIR}}/nvim.appimage"
    state: link
  become: yes

- name: "Add {{NEOVIM_BIN_DIR}} To PATH"
  ansible.builtin.lineinfile:
    path: "/etc/zsh/zshenv"
    line: "export PATH={{NEOVIM_BIN_DIR}}:$PATH"
    create: yes
  become: yes

- name: "Add AppImage Dependency"
  ansible.builtin.package:
    state: latest
    name: libfuse2
  become: yes

