---
- name: "Install NeoVim"
  community.general.homebrew:
    state: latest
    name: neovim

- name: "Create {{ neovim_config_dir | dirname }}"
  ansible.builtin.file:
    path: "{{ neovim_config_dir | dirname }}"
    state: directory
    mode: "0755"

- name: "Symlink {{ neovim_config_dir }}"
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    path: "{{ neovim_config_dir }}"
    state: link
    force: true

- name: "Create pyenv Virtualenv For NeoVim"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      pyenv virtualenv {{ pyenv_python_versions[-1] }} neovim
  args:
    creates: "{{ ansible_facts['env'].HOME }}/.pyenv/versions/neovim"

- name: "Install pynvim In NeoVim Virtualenv"
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      pyenv activate neovim
      pip install --upgrade pynvim
  changed_when: false

- name: "Config Shell Env"
  ansible.builtin.blockinfile:
    path: "{{ shared_env_sh.dest }}"
    create: true
    mode: "0644"
    marker: "#### {mark} ANSIBLE MANAGED BLOCK - {{ playbook_dir | basename }}/roles/{{ role_name }} ####"
    block: source {{ role_path }}/files/nvim.sh
