---
- name: "Git Clone catppuccin/iterm"
  ansible.builtin.git:
    repo: https://github.com/catppuccin/iterm.git
    dest: "{{ ansible_facts['env'].HOME }}/.catppuccin-iterm"
    version: b2936a6e55270fcc55421b1bb7d5fd194a489591
  register: colorscheme_catppuccin_iterm_repo

- name: "Import Catppuccin Mocha Color Scheme into iTerm2" # noqa: no-handler
  ansible.builtin.command:
    cmd: open "{{ ansible_facts['env'].HOME }}/.catppuccin-iterm/colors/catppuccin-mocha.itermcolors"
  changed_when: true
  when: colorscheme_catppuccin_iterm_repo.changed
