name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "debian"]
    steps:
      - uses: actions/checkout@v3
      - name: "setup ${{ matrix.os }}"
        run: "./containerize.sh ${{ matrix.os }}:latest"
      
