name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/runner/.nerd-fonts
          key: ${{ matrix.os }}
      - name: setup
        run: ./setup.sh
      
