name: Debian
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Debian"
        run: "./containerize.sh --runtime=podman --distro=debian --tag=latest"

